dogcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name ='about'),
    path('dogs/', views.dogs_index, name='index'),
    path('dogs/<int:dog_id>/', views.dogs_detail, name='detail'),
    path('dogs/create/', views.DogCreate.as_view(), name='dogs_create'),
    path('dogs/<int:pk>/update', views.DogUpdate.as_view(), name='dogs_update'),
    path('dogs/<int:pk>/delete', views.DogDelete.as_view(), name='dogs_delete'),
    path('dogs/<int:dog_id>/add_feeding', views.add_feeding, name='add_feeding'),
    path('dogs/<int:dog_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
import datetime
from datetime import date

# Create your models here.
class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})

class Dog(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'dog_id': self.id})
    
    def fed_for_today(self):
        return self.feeding_set.filter(date=date.today()).count() >= len(MEALS)

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Feeding(models.Model):
    date = models.DateField(verbose_name='Feeding Date', default=datetime.date.today)
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0])
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.get_meal_display()} on {self.date}'
    
    class Meta: 
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm 
from .models import Feeding 

class FeedingForm(ModelForm):
    class Meta: 
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Dog, Toy
from .forms import FeedingForm

class ToyList(ListView):
    model = Toy

class ToyDetail(DetailView):
    model = Toy

class ToyCreate(CreateView):
    model = Toy
    fields = '__all__'

class ToyUpdate(UpdateView):
    model = Toy

class ToyDelete(DeleteView):
    model = Toy
    success_url = '/toys/'

class DogDelete(DeleteView):
    model = Dog
    success_url = '/dogs/'

class DogUpdate(UpdateView): 
    model = Dog
    fields = ['breed', 'description', 'age'] 

class DogCreate(CreateView):
    model = Dog
    fields = ['name', 'breed', 'description', 'age']

def add_feeding(request, dog_id):
    form = FeedingForm(request.POST)
    if form.is_valid():
        new_feeding = form.save(commit=False)
        new_feeding.dog_id = dog_id
        new_feeding.save()
    return redirect('detail', dog_id = dog_id)

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def dogs_index(request):
    dogs = Dog.objects.all()
    return render(request, 'dogs/index.html', {'dogs': dogs})

def dogs_detail(request, dog_id):
    dog = Dog.objects.get(id=dog_id)
    toys_dog_doesnt_have = Toy.objects.exclude(id__in = dog.toys.all().values_list('id'))
    feeding_form = FeedingForm()
    return render(request, 'dogs/detail.html', {
        'dog': dog, 
        'feeding_form': feeding_form,
        'toys': toys_dog_doesnt_have
        })

def assoc_toy(request, dog_id, toy_id):
    Dog.objects.get(id=dog_id).toys.add(toy_id)
    return redirect('detail', dog_id=dog_id)

main_app/templates/about.html
{% extends 'base.html' %}


{% block content %}
<h1>About the Dog Collector</h1>
<hr />
<p>Hire the Dog Collector!</p>
{% endblock  %}
    

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dog Collector</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body class="d-flex flex-column h-100 bg-light">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark shadow" style="background-color: #008080;">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">
                    <i class="fa-solid fa-dog"></i>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbar">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'about' %}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'index' %}">View All My Dogs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'dogs_create' %}">Create Dog</a>
                        </li>
                    </ul>
                </div>
            </div>

        </nav>
    </header>
    <main class="flex-shrink-0">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="footer mt-auto py-3 footer-dark text-end shadow" style="background-color: #008080;">
        <div class="text-white">All Rights Reserved, &copy; 2022 Dog Collector &nbsp;</div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/cc4b206bd5.js" crossorigin="anonymous"></script>
</body>

</html>

main_app/templates/dogs/detail.html
{% extends 'base.html' %}


{% block content %}
<h1 class="text-center">Dog Details</h1>
</br></br></br>
<div class="container">
    <div class="row align-items-start">
        <div class="card col">
            <h3 class="card-title text-primary text-center">{{ dog.name }}</h3>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Breed: {{ dog.breed }}</li>
                <li class="list-group-item">Description: {{ dog.description }}</li>
                {% if dog.age > 0 %}
                <li class="list-group-item">Age: {{ dog.age }}</li>
                {% else %}
                <li class="list-group-item">Age: Pup</li>
                {% endif %}
            </ul>
            <br>
            <a class="btn btn-outline-dark border border-3" style="width: 10rem; background-color: #f3cfc6;" href="{% url 'dogs_update' dog.id %}">Edit</a>
            <br>
            <a class="btn btn-outline-dark border border-3 mb-2" style="width: 10rem; background-color: #f3cfc6;" href="{% url 'dogs_delete' dog.id %}">Delete</a>
        </div>
        <div class="col offset-md-2">
            <form class="form-control" action="{% url 'add_feeding' dog.id %}" method="POST">
                {% csrf_token %}
                {{ feeding_form.as_p }}
                <input type="submit" class="btn btn-outline-dark border border-3" style="background-color: #f3cfc6" value="Add Feeding">
            </form>
            <br>
            {% if dog.fed_for_today %}
            <div class="alert alert-success text-center">{{ dog.name }} has been fed all meals for today!</div>
            {% else %}
            <div class="alert alert-danger text-center">{{ dog.name }} might be hungry!</div>
            {% endif %}
            <table class=" table table-striped">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Meal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for feeding in dog.feeding_set.all %}
                    <tr>
                        <td>{{ feeding.date }}</td>
                        <td>{{ feeding.get_meal_display }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<hr>
<div class="container">
    <div class="row align-items-start">
        <div class="col-4">
            <h3>{{ dog.name }}'s Toys</h3>
            {% if dog.toys.count %}
            {% for toy in dog.toys.all %}
            <div class="card">
                <div class="card-body">
                    <span class="card-title">
                        A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
                    </span>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h5>No Toys :(</h5>
            {% endif %}
        </div>
        <div class="col-4 offset-md-3">
            <h3>Available Toys</h3>
            {% if toys.count %}
            {% for toy in toys.all %}
            <div class="card">
                <div class="card-body d-flex flex-row justify-content-between">
                    <span class="card-title">
                        A <span style="color: {{toy.color}}">{{ toy.color }}</span> {{ toy.name }}
                    </span>
                    <form action="{% url 'assoc_toy' dog.id toy.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-dark border border-3" style="background-color:#f3cfc6;">Add</button>
                    </form>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h5>{{ dog.name }} Already Has All Toys Available</h5>
            {% endif %}
        </div>
    </div>
</div>
<br>

<script>
    const dateEl = document.querySelector('#id_date');
    dateEl.type = 'date';

    const selectEl = document.querySelector('#id_meal');
    selectEl.className = 'form-select';
</script>


{% endblock %}

main_app/templates/dogs/index.html
{% extends 'base.html' %}


{% block content %}
<br>
<h1 class="text-center">Dog List</h1>
<br>
{% for dog in dogs  %}
    <div class="card container" style="width: 25rem;">
        <a href="{% url 'detail' dog.id %}">
            <div class="card-body">
                <h5 class="card-header text-center">{{ dog.name }}</h5>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Breed: {{ dog.breed }}</li>
                    <li class="list-group-item">Description: {{ dog.description }}</li>
                    {% if dog.age > 0 %}
                        <li class="list-group-item">Age: {{ dog.age }}</li>
                    {% else %}
                        <li class="list-group-item">Age: Pup</li>
                    {% endif %}
                </ul>  
            </div>
        </a>
    </div>
<br> 
{% endfor %}
    
    
{% endblock %}
    

main_app/templates/home.html
{% extends 'base.html' %}


{% block content %}
<h1>Home Page</h1>
{% endblock %}
    

main_app/templates/main_app/dog_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
<div class="d-flex flex-column align-items-center">
    <h1>Delete Dog</h1>
</br></br>
    <h4>Are you sure you want to delete {{ object.name }}?</h4>
</br></br>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Goodbye Doggo" class="btn btn-outline-dark border border-3" style="background-color:#f3cfc6;">&nbsp;
        <a href="{% url 'detail' dog.id %}">Cancel</a>
    </form>
</div>
    
{% endblock %}
    

main_app/templates/main_app/dog_form.html
{% extends 'base.html' %}


{% block content %}
<div class="text-center">
    {% if object %}
    <h1>Edit <span class="text-primary">{{ object.name }}</span></h1>
{% else %}
    <h1>Add Dog</h1>
{% endif %}
</div>
</br></br>
<div class="d-flex flex-column align-items-center justify-content-center">
    <form action="" method="post">
        {% csrf_token %}
        <table class="table vertical-align:middle">
            {{ form.as_table }}
        </table>
    </br>
        <div class="d-flex justify-content-center">
            <input type="submit" value="Submit!" class="btn btn-outline-dark border border-3" style="background-color:#f3cfc6;">
        </div>
    </form>
    
</div>

<script>
    const nameEl = document.querySelector('#id_name');
    nameEl.className = 'form-control';

    const breedEl = document.querySelector('#id_breed');
    breedEl.classList.add('form-control', 'form-control-md');

    const descEl = document.querySelector('#id_description');
    descEl.className = 'form-control';

    const numEl = document.querySelector('#id_age');
    numEl.className = 'form-control';
    
</script>
    
{% endblock %}
    